/// Flutter icons SupervielleIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SupervielleIcons
///      fonts:
///       - asset: fonts/SupervielleIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SupervielleIcons {
  SupervielleIcons._();

  static const _kFontFam = 'SupervielleIcons';
  static const String _fontPackage = 'spv_theme';

  static const IconData ask_for_money_modo = IconData(0xe800, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData benefits = IconData(0xe801, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData bullet = IconData(0xe802, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData calendar = IconData(0xe803, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData camera = IconData(0xe804, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData cash_out = IconData(0xe805, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData chart = IconData(0xe806, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData chat = IconData(0xe807, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData check = IconData(0xe808, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData chevron_left = IconData(0xe809, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData chevron_right = IconData(0xe80a, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData close = IconData(0xe80b, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData close_mini = IconData(0xe80c, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData coin = IconData(0xe80d, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData copy = IconData(0xe80e, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData credit_card = IconData(0xe80f, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData cuotificacion = IconData(0xe810, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData document = IconData(0xe811, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData face_id = IconData(0xe812, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData edit = IconData(0xe813, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData filter = IconData(0xe814, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData flag = IconData(0xe815, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData folder = IconData(0xe816, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData frame = IconData(0xe817, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData heart = IconData(0xe818, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData heart_filled = IconData(0xe819, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData hide = IconData(0xe81a, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData home = IconData(0xe81b, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData human_chat = IconData(0xe81c, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData info = IconData(0xe81d, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData key = IconData(0xe81e, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData linechart_up = IconData(0xe81f, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData loan = IconData(0xe820, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData lock = IconData(0xe821, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData logout = IconData(0xe822, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData menu = IconData(0xe823, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData more = IconData(0xe824, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData phone = IconData(0xe825, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData plus = IconData(0xe826, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData qr_modo = IconData(0xe827, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData recipe = IconData(0xe828, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData refresh = IconData(0xe829, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData reload = IconData(0xe82a, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData replace = IconData(0xe82b, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData saving = IconData(0xe82c, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData scan = IconData(0xe82d, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData search = IconData(0xe82e, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData seguros = IconData(0xe82f, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData send_money_modo = IconData(0xe830, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData shield = IconData(0xe831, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData setting = IconData(0xe832, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData show = IconData(0xe833, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData table = IconData(0xe834, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData touch_id = IconData(0xe835, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData unlock = IconData(0xe836, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData user = IconData(0xe837, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData users = IconData(0xe838, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData video = IconData(0xe839, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData warning = IconData(0xe83a, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData browser = IconData(0xe83b, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData alert = IconData(0xe83c, fontFamily: _kFontFam,  fontPackage: _fontPackage);
  static const IconData arrows = IconData(0xe83d, fontFamily: _kFontFam,  fontPackage: _fontPackage);
}
